sudo: required
services:
  - docker

before_install:
  - 'docker build -t blalasaadri/react-test -f ./client/Dockerfile.dev ./client'

script:
  - 'docker run blalasaadri/react-test npm test -- --ci --coverage'

after_success:
  - 'docker build -t blalasaadri/docker-tutorial-multi-client ./client'
  - 'docker build -t blalasaadri/docker-tutorial-multi-nginx ./nginx'
  - 'docker build -t blalasaadri/docker-tutorial-multi-server ./server'
  - 'docker build -t blalasaadri/docker-tutorial-multi-worker ./worker'
  # Log in to the docker CLI
  - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin'
  # Take those images and push them to dockerhub
  - 'docker push blalasaadri/docker-tutorial-multi-client'
  - 'docker push blalasaadri/docker-tutorial-multi-nginx'
  - 'docker push blalasaadri/docker-tutorial-multi-server'
  - 'docker push blalasaadri/docker-tutorial-multi-worker'